### ISSUE TITLE
Question: what are the 'requirements' included in the prompt, and where do they come from?

### ISSUE THREAD

**Issue by kingb12** [suntea233/DuetSim-User-Simulator-with-Dual-Large-Language-Models-for-Task-Oriented-Dialogues#1]
Hi! I recently read your paper and enjoyed the work. I had a clarification question I was having a hard time with: in section 3.1, it's mentioned that the prompt which generates the next user utterance is given a set of requirements for the response:

> while the requirements $R^G = [R^G_1 , R^G_2 , ..., R^G_n ]$ specify the desired properties of the generated response

I was wondering what an example of these might be, and where do they come from? Are they the same for all turns in a dialogue, generated by an LLM, or generated some other way?

Thanks, and thanks for sharing your code! If there's a place in the code I can look for an example, that would be awesome.

**Comment by suntea233** [comment]
Hi, thank you for your question!

All the requirements are human-crafted. The requirements for each conversation may slightly differ depending on the choice made in the previous step. 

Since we generate dialogue actions progressively, the domain requirements, for instance, will depend on the intent selected during domain generation.

Intent requirements can be found in: https://github.com/suntea233/DuetSim/blob/faeb3c287882f8b264c32e01add2fa0d29fca71f/user_simulator.py#L137

And domain requirements can be found in:
https://github.com/suntea233/DuetSim/blob/faeb3c287882f8b264c32e01add2fa0d29fca71f/user_simulator.py#L152

Other requirements can also be found in the code.

I hope this clarifies, let me know if you have further concerns. Thank you!

**Comment by kingb12** [comment]
Ah awesome, thank you for the pointers!
